/*

buySAFE Rollover Core
Copyright 2017, buySAFE, Inc.
$Revision: 1.127 $
*/
var bs_R=window.bs_R||{},buySAFE=window.buySAFE||{},_GUARANTEE=window._GUARANTEE||buySAFE;
(function(a,b){if(!a.sRoot){a.sRootHost="https://seal.buysafe.com";a.sRoot=a.sRootHost+"/private/rollover/";for(var d=document.getElementsByTagName("script"),c=0;c<d.length;c++){var e=d[c].src.substr(0,100);if(e=e.match(/((.*)\/private\/.*\/)rollover(?:\.unpacked)?\.js/i)||e.match(/()(.*)\/Web\/Seal\/gjs.aspx/i)){a.sRootHost=e[2];a.sRoot=e[1]||a.sRootHost+"/private/rollover/";break}}}a.aExecQ=a.aExecQ||[];a.onEvent=function(a,d,c){if(a){var b=a.addEventListener;a=a.attachEvent;b?b(d,c,!1):a&&a("on"+
d,c)}};a.onLoad=function(d,c){if(a.fOnLoad||c)d&&d();else a.onEvent(window,"load",d)};a.AddJS=function(a,d){var c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;window.setTimeout(function(){var a=document.getElementsByTagName("script")[0];a&&a.parentNode&&a.parentNode.insertBefore(c,a)},d||0)};b.Loaded||(b.Hash||(b.Hash=""),b.Guarantee||(b.Guarantee={order:"",total:"",email:""}),b.Seal||(b.Seal={bgcolor:"#FFFFFF"}),b.Button||(b.Button={bgcolor:"#FFFFFF"}),b.Loaded=1)})(bs_R,
buySAFE);var buySAFESealConfig=buySAFE.Seal,buySAFEButtonConfig=buySAFE.Button;bs_R._gel=function(a){return document.getElementById(a)};bs_R._geln=function(a){return document.getElementsByName(a)};bs_R._gelt=function(a){return document.getElementsByTagName(a)};bs_R._cel=function(a){return document.createElement(a)};bs_R._efp=function(a,b){return document.elementFromPoint(a,b)};bs_R._en=encodeURIComponent;bs_R._l=document.location;bs_R._st=function(a,b){return window.setTimeout(a,b)};
(function(a,b){a._ctx=function(d){d.oncontextmenu=function(){return!1};d.setAttribute(a.sNoPin,!0)};a.Trim=function(a){return String(a).replace(/^\s+|\s+$/g,"")};a.Hash=function(){return a.Trim(b.Hash)};a.warn=a.log=function(d,c){if(window.console&&console.log&&d){d.unshift(((new Date-a.T0)/1E3).toFixed(3));if(c)for(var b in c)d.push(b+":["+c[b]+"]");console.log(d)}};a.err=function(d,c){c&&(d+=": "+c.message);a._st(function(){throw Error("Guarantee: "+d);},0)};a.trc=function(d){a.AltSealInfo("bs_R.trcFn",
d.src,d.name,a.Hash(),"","Large","",{src:d.src,name:d.name})};a.trcFn=function(){};a.GetXml=function(a){var c;window.DOMParser?c=(new DOMParser).parseFromString(a,"text/xml"):(c=new ActiveXObject("Microsoft.XMLDOM"),c.async="false",c.loadXML(a));return c};a.EncodeQuery=function(d){var c=[],b;for(b in d){var f=d[b]||{},g;for(g in f){var h=f[g]||"",h="encode"==b?a._en(h):h,h="PR"==g?h.substr(0,1024):h;c.push(g+"="+h)}}return c.join("&")};a.isUndef=function(a,c){return"undefined"==typeof a?c:a};a.Bool=
function(a){return a&&"true"==a.toLowerCase()};a.Important=function(a){return a.replace(/;/g,"!important;")};a.GetCookieRaw=function(a){for(var c=document.cookie.split("; "),b=0;b<c.length;b++){var f=c[b].indexOf("="),g=c[b].substring(0,f),f=c[b].substring(f+1);if(a==g)return f}return null};a.GetCookie=function(d){return(d=a.GetCookieRaw(d))?unescape(d):d}})(bs_R,buySAFE);
function buysafe_set_cookie(a,b,d,c,e,f){a=a+"="+escape(b);d&&(b=new Date,b.setTime(b.getTime()+864E5*d),a+="; expires="+b.toGMTString());c&&(a+="; path="+escape(c));e&&(a+="; domain="+escape(e));f&&(a+="; secure");document.cookie=a}bs_R.AddBody=function(a){var b=document.body;if(b){var d=b.firstChild;d&&b.insertBefore(a,d)}};bs_R.GetCreateTag=function(a,b){var d=bs_R._gel(a)||bs_R._cel(b||"span");d.id=a;return d};
bs_R.GetAddTag=function(a,b){var d=bs_R.GetCreateTag(a,b);d.parentNode||bs_R.AddBody(d);return d};bs_R.BottomSpacer=function(a){bs_R.onLoad(function(){var b=bs_R.GetCreateTag("buySAFE Spacer","div");a>b.offsetHeight&&(b.style.height=a+"px");document.body.appendChild(b)})};
bs_R.GetByClass=function(a,b){if(document.querySelectorAll)return document.querySelectorAll((b||"")+"."+a);for(var d=bs_R._gelt(b||"*"),c=[],e=" "+a+" ",f=0;f<d.length;f++){var g=d[f];g.className&&0<=(" "+g.className+" ").indexOf(e)&&c.push(g)}return c};bs_R.GetStyle=function(a,b){if(a){var d=a.currentStyle||document.defaultView&&document.defaultView.getComputedStyle(a,null)||{};return b?d[b]:d}};
bs_R.SetTopMost=function(a,b){b=b||0;if(a&&a.getBoundingClientRect&&!buySAFE.NoOnTop){var d=a.style,c=function(a){return Number(bs_R.GetStyle(a,"zIndex"))||0},e=function(a){if(a&&!String(a.id).match(/^_guarantee|buysafe|bsg_iframe/i)){var d=a.parentNode;d&&d.style&&(a=(d=e(d))&&c(d)>=c(a)?d:a);return a}},f=function(b){if(b){var e=c(b),f=c(a);e>=d.zIndex&&(d.zIndex=bs_R.nZIndex=e+1,c(a)==e&&f<e&&(d.zIndex=bs_R.nZIndex=10*e));return b}},g=a.getBoundingClientRect(),h=bs_R.oDocElem,k=Math.max(g.top,0),
l=Math.min(g.right,h.clientWidth)-1,h=Math.min(g.bottom,h.clientHeight)-1,g=Math.max(g.left,0);f(e(bs_R._efp(g,k)));f(e(bs_R._efp(l,k)));f(e(bs_R._efp(g,h)));f(e(bs_R._efp(l,h)));f(e(bs_R._efp(parseInt((g+l)/2),parseInt((k+h)/2))));10>b&&bs_R._st(function(){bs_R.SetTopMost(a,++b)},1E3)}};
bs_R.getDevicePrint=function(a){a=a||{};var b=buySAFE,d=b.setIpDefinition;b.Variation&&(a.sno=b.Variation);b.VariationName&&(a.snn=b.VariationName.replace(/[;=\s]+/g," "));d&&d.tn&&(a.tn=d.tn);!a.sno||bs_R.oSealRS.DisplayFlag&1024||(a.ipo=1);b=bs_R.oBrowser;b="br="+b.name+";vr="+b.version+";os="+b.os;for(name in a)b+=";"+name+"="+a[name];return bs_R._en(b)};bs_R.isDupe=function(a){if(bs_R.oObjs[a])return bs_R.warn(["Guarantee: Skipping duplicate request",a]),1;bs_R.oObjs[a]=1;return 0};
bs_R.oBSG=bs_R.oBSG||{aSizeQueue:[],id:"BSG_Iframe",idfix:"BSG_Iframe_Fix"};bs_R.oBSG.Size=function(a){var b=bs_R.oBSG;b.fSizing=1;var d=(new Date).valueOf(),c=b.aSizeQueue[0];c.start||(c.start=d,c.end=c.start+c.time,c.orig=parseInt(a.height));a.height=c.orig+parseInt((c.target-c.orig)*(d<c.end?(d-c.start)/c.time:1))+"px";d>=c.end&&(b.aSizeQueue.shift(),bs_R.SetTopMost(b.span));b.aSizeQueue.length?bs_R._st(function(){b.Size(a)},20):b.fSizing=0};
bs_R.oBSG.Queue=function(a){var b=bs_R.oBSG;b.timerHide&&(clearTimeout(b.timerHide),b.timerHide=0);b.oFrame&&(b.aSizeQueue.push({target:a,time:500}),b.fSizing||b.Size(b.oFrame))};bs_R.oBSG.Show=function(){bs_R.oBSG.Queue(bs_R.oBSG.nHeightShow)};bs_R.oBSG.Hide=function(){bs_R.oBSG.Queue(bs_R.oBSG.nHeightHide)};bs_R.oBSG.Toggle=function(){var a=bs_R.oBSG,b=bs_R._gel(a.idIMG),d=a.fClosed;b&&(b.style.backgroundPosition="-95px "+(d?"-25px":"-40px"),d?a.Show():a.Hide(),a.fClosed=!d)};
bs_R.oBSG.OnLoad=function(){var a=bs_R.oBSG;a.fLoaded||(a.fLoaded=1,a.oFrame=bs_R._gel(a.id),a.fnAutoShow(),a.nAutoHide&&a.fnAutoHide&&(a.timerHide=bs_R._st(function(){a.fnAutoHide()},a.nAutoHide)))};
bs_R.oBSG.WriteResponsive=function(a,b,d){b=bs_R.oBSG;var c=bs_R.sRespID,e=bs_R._gel(c);e.src=e&&"Seal"==a?bs_R.sWeb4+"StoreInfo?MPHASH="+d.MPUHash:bs_R.sWeb4+"Guarantee?"+bs_R.EncodeQuery({encode:{gn:b.oRS.GuaranteeNumber,e:b.oRS.Email},raw:{hash:bs_R.Hash()}});if(a=bs_R._gel(c+"_close"))a.onclick=function(){this.style.background="#5c5c5c";buysafeOut(0,1)}};bs_R.oBSG.WriteFrame2=function(a,b){bs_R.oBSG.oRS=b;bs_R.oBSG.WriteFrame(a,b.ContentName)};
bs_R.oBSG.WriteFrame=function(a,b,d){if(b){var c=bs_R.oBSG,e=buySAFE,f=e.Guarantee,g=f.inline;d=d||0;var h=bs_R.GetAddTag(bs_R.sBSGID),k=c.oRS.GuaranteeNumber,k=k.match(/^09NSG/)?bs_R.sNSG:k.match(/^09GRT/)?bs_R.sBSG:"Guarantee";if(f.hidden)(new Image).src=c.url+"&IMAGE=BLANK";else if("V3"==e.Version||b.match(/responsive/i)){bs_R.fWS||e.WriteSeal();f=bs_R.oSealRS;e=bs_R.oRollover;bs_R.nResponsiveH="370px";e.HTML.Responsive=bs_R.WriteHTMLVAR(e.RAW.Responsive);var e=e.HTML.Responsive,l;f.SealDone&&
f.SealName&&e&&"pending"!=e&&(l=bs_R._gel(f.SealName+"_a"))?g?(c.span=h,h.innerHTML='<iframe id="'+bs_R.sRespID+'" title="'+k+' iFrame" src="" style="width:inherit;height:inherit;border:0;overflow:hidden;" frameborder="0" border="0" scrolling="no"></iframe>',bs_R.oBSG.WriteResponsive("Guarantee","Responsive",f)):(bs_R.RollAttach([l],"Responsive","Guarantee"),buysafeOver("Responsive",l,"Guarantee","",1)):40>d&&bs_R._st(function(){bs_R.oBSG.WriteFrame(a,b,d+1)},500)}else{l=a+"_iFrameFix";c.span=h;e=
h.style;h.innerHTML="";var m=bs_R._cel("div");m.id=a+"_div";var n=m.style;n.display=e.display="block";n.visibility=e.visibility="visible";bs_R.fnCSS(n);bs_R.fnCSS(e);var r=f.minimize,p=g?"background:none transparent;height:0;width:0;":"background:url('"+bs_R.sRootSealImgBSG+"shadow.png') no-repeat;height:10px;width:10px;",s=g?0:14,v="",u="",q="",w="0",x=0;c.fClosed=1;c.idTXT=a+"_TXT";c.idIMG=a+"_IMG";var t=bs_R.sCSS,q=t+"height:auto;width:auto;";b.match(/^..._Feedback/i)?(c.nAutoHide=0,c.fnAutoHide=
c.fnAutoShow=c.Toggle,c.nHeightShow=282,c.nHeightHide=50,c.nWidth=c.nWidth||700,n.width=e.width=c.nWidth+s+"px",g||(bs_R.SetPersist({ele:h,sPosition:"BCL",Z:100}),w="2px 2px 0 2px",x=4),u=bs_R.sTable+'><tr style="'+q+'"><td style="'+t+p+'width:auto;"></td><td style="'+t+p+'background-position:right top;"></td></tr><tr style="'+q+'"><td style="'+q+'">',g||(v='<div style="'+t+'clear:right;">'+bs_R.sTable+' align="right" style="position:relative;width:100%;padding:3px 4px 0;cursor:pointer;font-size:9px;" onclick="bs_R.oBSG.Toggle();"><tr style="'+
q+'"><td style="'+t+'text-align:center;height:16px;"><span id="'+c.idIMG+'" style="display:inline-block;height:15px;width:61px;margin:-1px 0 -1px 2px;background:transparent url('+bs_R.sRootSealImgBSG+'sprite_201110.png) no-repeat 0 20px;"></span></td></tr></table></div>'),q='</td><td style="'+t+p+'height:auto;background-position:-990px -10px;"></td></tr></table>'):(c.nAutoHide=5E3,c.fnAutoHide=c.Hide,c.fnAutoShow=c.Show,c.nHeightShow=140,c.nHeightHide=28,c.nWidth=826,g||bs_R.SetPersist({ele:h,sPosition:"BRL",
Z:-10}),m.onmouseover=function(){bs_R.RollOver(c.Show)},m.onmouseout=function(){bs_R.RollOut(c.Hide)},u=bs_R.sTable+'><tr style="'+q+'"><td style="'+t+p+'width:auto;"></td></tr><tr style="'+q+'"><td style="'+q+'">',q="</td></tr></table>");g?c.Show():0<r?c.nAutoHide=r:0>r&&(c.fClosed=0);m.innerHTML=u+'<div id="'+l+'" style="'+t+"position:relative;background:#f1f1f1;height:100%;width:"+(c.nWidth+x)+'px;"><div style="'+t+'position:absolute;top:0;left:0;background:#f1f1f1;width:100%;height:100%;z-index:-1;"></div>'+
v+'<div style="'+t+"clear:right;margin:"+w+";width:"+c.nWidth+'px;"><iframe src="'+c.url+'&HTML=1" id="'+a+'" title="'+k+' iFrame" name="'+a+'" width="'+c.nWidth+'" height="'+(g?c.nHeightShow:0)+'" onload="bs_R.oBSG.OnLoad();" '+bs_R.sFrameDef+"></iframe></div></div>"+q;h.appendChild(m);(g=bs_R._gel(l))&&bs_R.iFrameFix(l,g,"#f1f1f1");f.nospacer||bs_R.BottomSpacer(70)}bs_R.AddJS(bs_R.sRoot+"rollover.anywhere.js",100)}};buySAFE.WriteGuarantee=WriteBuySafeGuarantee;
function WriteBuySafeGuarantee(a,b){bs_R.sBSGID=b||bs_R.sBSGID;a=a||"JavaScript";bs_R.fWG=!0;if(!bs_R.isDupe(bs_R.sBSGID))bs_R.onLoad(function(){function d(a){var b="";if(b=bs_R._gel(a))b=b.value;!b&&(b=bs_R._geln(a))&&b[0]&&(b=b[0].value);return b}var c=buySAFE,b=c.Guarantee;b.total=b.subtotal||b.total;var f="",g="0",h="",k="";if("HTML"==a)f=d(b.order),g=d(b.total),h=d(b.email);else if("Yahoo"==a){window.orderNum&&(f=orderNum);window.orderSubTotal&&(g=orderSubTotal);var l;(l=bs_R._gel("ys_billToEmail"))&&
l.innerHTML&&(h=l.innerHTML)}else"ProStores"==a||"JavaScript"==a?(f=b.order||c.order||"",g=b.total||c.total||"",h=b.email||c.email||"",k=b.currency||c.currency||""):"ShopSite"==a?(window.ss_ordernum&&(f=ss_ordernum),window.ss_subtotal&&(g=ss_subtotal),window.ss_email&&(h=ss_email)):"Volusion"==a&&window.Order&&(Order[0]&&(f=Order[0]),Order[3]&&(g=Order[3]),Order[9]&&(h=Order[9]));g=String(g).replace(/[\$\s\,\+]+/g,"");h=String(h).match(/^\s*([^\s]*)/)[1];f=bs_R.Trim(f);k=bs_R.Trim(k);bs_R.oBSG.oRQ=
{total:g,email:h,order:f,currency:k};b=bs_R.oBSG;b.url=bs_R.sRootSeal+"Guarantee.aspx?"+bs_R.EncodeQuery({encode:{ifID:b.id,o:f,t:g,cc:k,e:c.NoEmailAddr?"":h},raw:{DP:bs_R.getDevicePrint(),HASH:bs_R.Hash()}});bs_R.AddJS(b.url+"&JSONP=1&cbf=bs_R.oBSG.WriteFrame2")},1)}bs_R.CheckBlank=function(a){try{if(43==a.fileSize||2==a.naturalWidth){var b=a.parentNode;"a"==b.tagName.toLowerCase()&&-1<b.href.indexOf("VerifySeal.aspx")&&(b.style.display="none")}}catch(d){}};
bs_R.TimeoutNew=function(a,b,d,c){bs_R.oTimeouts[a]={Target:d,Failed:!1,Interval:bs_R._st(b,c)}};bs_R.TimeoutFailed=function(a){a=bs_R.oTimeouts[a];clearInterval(a.Interval);a.Failed=!0};bs_R.TimeoutClear=function(a,b){clearInterval(bs_R.oTimeouts[a].Interval)};bs_R.WriteFlash=function(a,b,d,c){a=bs_R.GetAddTag(a);c&&(a.style.display="none");bs_R.TimeoutNew(b,d,a,buySAFE.SealDelay||0)};buySAFE.WriteButtonAjax=WriteBuySafeButtonAjax;
function WriteBuySafeButtonAjax(a){eval(a.substr(a.indexOf("WriteBuySafeButton"),a.indexOf("\x3c/script>")-a.indexOf("WriteBuySafeButton")))}buySAFE.WriteButtonAjaxInvisible=WriteBuySafeButtonAjaxInvisible;function WriteBuySafeButtonAjaxInvisible(a){eval(a.substr(a.indexOf("WriteBuySafeButtonInvisible"),a.indexOf("\x3c/script>")-a.indexOf("WriteBuySafeButtonInvisible")))}
bs_R.SWF_Vars=function(a){a=a.replace(/&amp;/gi,"&");a=a.split("&");for(var b={},d=0;d<a.length;d++){var c=a[d],e=c.indexOf("="),f=c.substring(0,e),c=c.substring(e+1);b[f]=c}return b};
bs_R.WriteButton=function(a,b,d,c,e,f){function g(a){return String.fromCharCode(a)}var h=bs_R.SWF_Vars(e);c=new Date;if(1==c.getDate()||1==(new Date(c.getTime()+864E5)).getDate()){e=65;var k=parseInt(c.getDate()*Math.random());h[bs_R.sT+"m"+g(e++)]=k;h[bs_R.sT+"m"+g(e)]=c.getDate()-k}h.Id&&(document.cookie="BSSCID="+h.Id+";");"Certified"==h.RolloverType&&bs_R.Bool(h.DefaultChecked)&&bs_R.Bool(h.Clickable)&&(h.RolloverType="Checked");"Invisible"==f?bs_R.WriteFlash(a,d,function(){bs_R.ButtonTimeoutInvisible(a,
d,b,h)}):bs_R.WriteFlash(a,d,function(){bs_R.ButtonTimeout(a,d,b,h)})};buySAFE.WriteButton=WriteBuySafeButton;function WriteBuySafeButton(a,b,d,c,e){bs_R.WriteButton(a,b,d,c,e,"Default")}buySAFE.WriteButtonInvisible=WriteBuySafeButtonInvisible;function WriteBuySafeButtonInvisible(a,b,d,c,e){bs_R.WriteButton(a,b,d,c,e,"Invisible")}
bs_R.GetAltButton=function(a,b,d,c,e){var f=d,f="Receipt"==e||"Seller"==e?f+"-bg-receipt.gif":c?f+"-bg-bonded.gif":f+"-bg-click.gif";return bs_R.sRootSeal+"AltButton.aspx?HASH="+a+"&I="+b+"&DP="+bs_R.getDevicePrint()+"&T="+(null==c?d:f+"&TS="+(new Date).valueOf())};bs_R.ButtonTimeoutInvisible=function(a,b,d,c){bs_R.TimeoutFailed(b);(new Image(1,1)).src=bs_R.GetAltButton(c.HASH,c.Id,"dot.gif")};
bs_R.ButtonTimeout=function(a,b,d,c){var e=c.BondCost;bs_R.TimeoutFailed(b);c.DefaultChecked=bs_R.Bool(c.DefaultChecked);c.Bondable=bs_R.Bool(c.Bondable);c.Clickable=bs_R.Bool(c.Clickable);var f=bs_R._gel(a);if(f){if(bs_R.fFlashPlaceholder||(f.innerHTML=""),c.Bondable){a=d.substring(d.lastIndexOf("/")+1).replace(".swf","");d=bs_R._cel("div");d.id="div_"+b;bs_R._ctx(d);var g=bs_R._cel("div");g.id="div_button_"+b;b=g.style;b.fontFamily="Arial, Helvetica, sans-serif;";b.backgroundRepeat="no-repeat";
b.textAlign="right";b.fontWeight="bold";b.color="#76777a";b.fontSize="10px";a.match(/^BuySafeButton_(?:4280|4348|4886|4900|5670c|5670b|5670a|5774)$/i)?(b.height="40px",b.width=bs_R.IsIE?"190px":"188px",b.paddingRight="2px",b.paddingTop="11px",e=""):a.match(/^BuySafeButton_[23]$/i)?(b.height="13px",b.width="185px",b.paddingRight="5px",b.paddingTop="27px"):(b.height=bs_R.IsIE?"40px":"32px",b.width=bs_R.IsIE?"185px":"175px",b.paddingRight="15px",b.paddingTop="8px",b.color="#0D2954",b.fontSize="14px");
g.oncontextmenu=d.oncontextmenu;var h=new Image;h.onload=function(){192==h.width&&(c.RolloverType="Free");var a="HASH="+c.HASH+"&CHECKED="+c.DefaultChecked+"&LearnMore="+c.LearnMoreUrl+"&RolloverType="+c.RolloverType;g.style.backgroundImage="url("+h.src+")";g.onmouseover=function(){buysafeOver(c.RolloverType,this,"Button",a)};g.onmouseout=function(){buysafeOut()}};c.Clickable?(b.cursor="pointer",c.DefaultChecked?h.src=bs_R.GetAltButton(c.HASH,c.Id,a,!0,c.RolloverType):(g.innerHTML=e,h.src=bs_R.GetAltButton(c.HASH,
c.Id,a,!1,c.RolloverType)),g.onclick=function(){window[c.Callback](String(!c.DefaultChecked).toLowerCase())}):h.src=bs_R.GetAltButton(c.HASH,c.Id,a,!0,c.RolloverType);d.appendChild(g);f.appendChild(d)}}else bs_R.err("WriteButton: Can't find element: "+a)};function SealLoadedCallback(a){bs_R.TimeoutClear(a,a+"_a")}function ButtonLoadedCallback(a){bs_R.TimeoutClear(a,"div_"+a)}
bs_R.GetTarget=function(a){var b={top:0,left:0,height:a.height?parseInt(a.height):a.offsetHeight,width:a.width?parseInt(a.width):a.offsetWidth,offsetWidth:a.offsetWidth,offsetHeight:a.offsetHeight};if(a&&a.getBoundingClientRect){var d=bs_R.oDocElem,c=document.body;a=a.getBoundingClientRect();var e=c.getBoundingClientRect(),c="relative"==bs_R.GetStyle(c).position,f=window.pageXOffset||d.scrollLeft,g=window.pageYOffset||d.scrollTop,h=c?e.top+g:0;b.left=a.left-(c?e.left+f:0)+f-d.clientLeft;b.top=a.top-
h+g-d.clientTop}return b};bs_R.AltSealTimeoutSSR=function(a,b,d,c){bs_R.TimeoutFailed(b);var e=bs_R._gel(a);if(e){bs_R.fFlashPlaceholder||(e.innerHTML="");a=bs_R._cel("a");a.href=bs_R.sWebVer+"?"+d;a.target="_blank";a.id=b+"_a";var f=bs_R._cel("img");f.src=bs_R.sRootVer+"AltSeal.aspx?"+d+"&S="+c;f.id=f.name=b+"_img";f.border=0;bs_R._ctx(f);a.appendChild(f);e.appendChild(a);bs_R.RollAttach(bs_R._geln(f.name),"TrustSeal","TrustSeal",d)}else bs_R.err("WriteTrustRatingSeal: Can't find element: "+a)};
bs_R.AltSealTimeout=function(a,b,d,c,e,f){bs_R.TimeoutFailed(b);bs_R.AltSealInfo("bs_R.AltSeal",a,b,d,c,e,f)};bs_R.ii=function(a){bs_R.oSealRS.UniqueIP=(a||{}).ii||0;for(bs_R.determineSet(bs_R.oSealRS,buySAFE);a=bs_R.iiQ.shift();)bs_R.AltSealInfo.apply(this,a)};
bs_R.AltSealInfo=function(a,b,d,c,e,f,g,h){if(0<=bs_R.oSealRS.UniqueIP){var k=new Date;bs_R.AddJS(bs_R.sRootSeal+"AltSealInfo.aspx?Info=1&"+bs_R.EncodeQuery({encode:{PR:document.referrer},raw:{CBF:a,Elem:b,SN:d,HASH:c,S:f,T:g,MSPHASH:e,DP:bs_R.getDevicePrint(h),I:bs_R.GetCookieRaw("BSSCID")||"",TS:k.valueOf()}}))}else bs_R.iiQ.push(arguments),1>=bs_R.iiQ.length&&bs_R.AddJS(bs_R.sRootSeal+"ii.aspx?CBF=bs_R.ii")};bs_R.HideAll=function(a){a.Guarantee.hidden=a.HideSeal=a.HideKickers=1};
bs_R.determineSet=function(a,b){if(b.EnableClientDisplay)if(a.DisplayFlag&1024){var d=b.setResDefinition,c=b.setIpDefinition;a.SNO||(a.SNO="a");if(d)for(var e=bs_R.oDocElem.clientWidth,f=d.screenRes,d=0;d<f.length;d++)e>=f[d].start&&(a.SNO=f[d].t);if(c)for(e=a.UniqueIP||0,c=c.setIp,d=0;d<c.length;d++)e>=c[d].start&&e<=c[d].end&&(a.SNO=c[d].t);b.Variation=a.SNO}else b.Variation=a.SNO=a.SetName};
bs_R.determineKickerName=function(a,b){var d=b.KickerResDefinition,c=b.KickerRxDefinition;if(d)for(var e=bs_R.oDocElem.clientWidth,f=d.screenRes,d=0;d<f.length;d++)e>=f[d].start&&(a.kn=f[d].t);if(c)for(a.kn=c.init,c=c.defRx,d=0;d<c.length;d++)RegExp(c[d].rx,"i").exec(c[d].v)&&(a.kn=c[d].t)};
bs_R.AltSealResponse=function(a,b){for(var d=bs_R,c=d.GetXml("<xml>"+a+"</xml>").getElementsByTagName("SealResponse")[0]||bs_R._cel("a"),e=d.oSealRS,e=d.oSealRS={SealDone:1,SealName:b,DisplayFlag:e.DisplayFlag,PartnerOvr:"",PartnerCol:"#00305E",PartnerHSR:"230",PartnerNam:d.sBSG},c=c.attributes,f=0;f<c.length;f++){var g=c[f];e[g.name]=g.value}e.MPUHash=bs_R._en(e.MarketplaceUserHash);e.ShowSeal=d.Bool(e.ShowSeal);e.UniqueIP=String(e.UniqueId).split("_")[1]||0;c=buySAFE;c.Variation&&(e.SNO=c.Variation);
e.ShowSeal||(e.SealLocation="");var h=e.SealLocation;h&&(h.match(/\/Web\/Seal\/Flash\/(.*).swf/i)&&(e.Seal=d.sRootSealImg+RegExp.$1+".png"),h.match(/([TB][LR][LMSX])\.swf$/i)&&(e.Corner=RegExp.$1),h.match(/AttentionRequired.*swf$/i)&&d.Bool(e.PersistantSealOn)&&(e.Corner="BLS"),h.match(/^Custom.*?\[(\d+)\]\/(.*MP(\d+)\w*)_Seal_...\.swf$/i)&&(e.Custom=d.sRootHost+"/"+RegExp.$2,e.Serial=RegExp.$3,e.Partner=RegExp.$1,"11"==e.Partner&&(e.PartnerOvr="11",e.PartnerCol="#333333",e.PartnerHSR="175",e.PartnerNam=
d.sNSG),d.determineSet(e,c),"off"==e.SNO?(e.ShowSeal=0,d.HideAll(c)):e.SNO&&e.SetName&&(e.Custom=e.Custom.replace(RegExp(e.SetName+"$","i"),e.SNO),e.SetName=e.SNO),e.Partner&&e.Serial&&(e.Stream=d.sRootSeal+"si.aspx?s="+e.Serial+"&p="+e.Partner+"&t="+e.SetName),e.Seal=e.Custom+"_Seal_"+e.Corner+".png",e.fCustom=e.RolloverName.match(/^custom/i),e.fCustom&&"V3"==c.Version&&(e.RolloverName="Responsive")));bs_R._st(d.WriteKickers,d.nKickTime);d.onLoad(d.WriteKickers);var k=c.Callback;k&&"function"==typeof k&&
bs_R._st(function(){k(h?e.RolloverName:"")},100);return e};
bs_R.AltSeal=function(a,b,d,c,e,f,g){g=bs_R.AltSealResponse(g,b);var h=g.RolloverType,k=g.RolloverName,l=g.Stream,m=bs_R._gel(a);if(m){bs_R.fFlashPlaceholder||(m.innerHTML="");l&&(l+="&R=0&x="+g.Corner);var l=l||g.Seal||bs_R.sRootSeal+"AltSeal.aspx?"+bs_R.EncodeQuery({encode:{PR:document.referrer},raw:{HASH:d,S:e,T:f,MSPHASH:c,X:"png",DP:bs_R.getDevicePrint(),I:bs_R.GetCookieRaw("BSSCID")||"",TS:(new Date).valueOf()}}),n=function(a){function b(d){var e="none"==a.style.display,f=a.style;e&&(f.visibility=
"hidden",f.display="inline");var g=bs_R.sRollText+"width:100%;text-align:center;color:#ffffff;font-weight:400;bottom:"+(bs_R.IsFF?1:0)+"px;left:-1px;"+(70<a.offsetWidth?"height:14px;line-height:12px;font-size:10px;font-size-adjust:0.5;":"height:12px;line-height:10px;font-size:8px;");e&&(f.display="none",f.visibility="visible");c.style.cssText=bs_R.Important(g);c.innerHTML=d}var c=bs_R._cel("div");c.className="buysafe buysafe_seal buysafe_date";bs_R._ctx(c);b("verifying...");bs_R._st(function(){b(bs_R.sDate)},
1E3);a.appendChild(c)};e=bs_R._cel("img");e.id=e.name=b+"_img";e.alt=g.PartnerNam||"Guarantee Seal";g.fCustom&&(e.onload=function(){n(m)});e.src=l;e.border=0;bs_R._ctx(e);l=bs_R._cel("a");l.target="_blank";l.style.fontSize="0";l.id=b+"_a";l.tabIndex=-1;bs_R.oRollNames[e.id]=k;g.SealLocation&&g.ShowSeal?g.Corner?(e.corner=g.Corner,bs_R.AdjustSeal(a,b,"AltSeal",2,1,e.corner),e.style.verticalAlign="bottom"):bs_R.AdjustSeal(a,b,"AltSeal",0,0):bs_R.AdjustSeal(a,b,"AltSeal",0,1,"BRS");a=buySAFE.NoSealRollover;
"Responsive"==k?(e.id=l.id,e.style.cursor="pointer",m.appendChild(e),a||bs_R.RollAttach([e],k,"Seal")):h&&"DoesNotApply"!=h?(l.href=bs_R.sVerify+"?PublicToken="+d+"&MSPHASH="+c+("Guarantee"==h?"&G=1":""),l.appendChild(e),m.appendChild(l),a||bs_R.RollAttach([e],k||("M"==f?"Certified":"GenericT"),"Seal")):m.appendChild(e)}else bs_R.err("AltSeal: Can't find element: "+a);g.UniqueId&&buysafe_set_cookie("buySAFEUID","BSUID::"+g.UniqueId,"Guarantee"==h?-1:364,"/")};buySAFE.WriteTrusteeSeal=WriteBuySafeTrusteeSeal;
function WriteBuySafeTrusteeSeal(a,b,d){}bs_R.getCSSRule=function(a,b){a=a.toLowerCase();if(document.styleSheets)for(var d=0;d<document.styleSheets.length;d++){var c=document.styleSheets[d],e=0,f=!1;do{if((f=c.cssRules?c.cssRules[e]:c.rules[e])&&f.selectorText.toLowerCase()==a)return"delete"==b?(c.cssRules?c.deleteRule(e):c.removeRule(e),!0):f;e++}while(f)}return!1};
function buysafeGetAffiliateURL(a,b,d,c,e,f){return bs_R.sRootVer+"Verify.aspx?"+bs_R.EncodeQuery({encode:{A:d,T:b,U:a,P:c,R:bs_R._l,PR:document.referrer,Q:e,N:f},raw:{}})}
function buySAFEAffiliate(a,b,d,c,e,f,g,h,k,l){this.ElementName=a;this.Size=b||"Small";this.TargetFullURL=d;this.TargetDomainURL=c;this.AffilateID=e;this.ProgramID=f;this.Query=g;this.SearchResultNumber=h;this.IsEcommerce=k;this.Rating=l;this.WriteSeal=function(){WriteBuySafeAffiliateSeal(this)};this.WriteTrustSeal=function(){WriteBuySafeTrustSeal(this)}}buySAFE.WriteAffiliateSeal=WriteBuySafeAffiliateSeal;
function WriteBuySafeAffiliateSeal(a,b,d,c,e,f,g,h){if(!bs_R.isDupe(a)){var k="buysafeSeal_"+ ++bs_R.nSeals;b="object"!=typeof a?new buySAFEAffiliate(a,b,d,c,e,f,g,h):a;(d=bs_R._gel(b.ElementName))?(c=bs_R._cel("a"),c.href=buysafeGetAffiliateURL(b.TargetFullURL,b.TargetDomainURL,b.AffilateID,b.ProgramID,b.Query,b.SearchResultNumber),c.target="_blank",c.id=k+"_a",a=bs_R._cel("img"),a.src=bs_R.sRootSeal+"SealVerify.aspx?"+bs_R.EncodeQuery({encode:{MerchantURL:b.TargetDomainURL,Q:b.Query,N:b.SearchResultNumber,
A:b.AffiliateID},raw:{}}),a.id=a.name=k+"_img",a.border=0,bs_R._ctx(a),c.appendChild(a),d.appendChild(c),k="MerchantURL="+bs_R._en(b.TargetDomainURL),bs_R.RollAttach(bs_R._geln(a.name),"Affiliate","Affiliate",k)):bs_R.err("WriteAffiliateSeal: Can't find element: "+a)}}bs_R.Debounce=function(a,b){var d=new Date;d>(bs_R.oDebounce[a]||0)&&(bs_R.oDebounce[a]=d.setMilliseconds(d.getMilliseconds()+250),bs_R._st(b,250))};bs_R.onDebounce=function(a,b,d,c){bs_R.onEvent(a,b,function(){bs_R.Debounce(d,c)})};
bs_R.CheckZoom=function(a,b){buySAFE.NoZoomCheck||(a.zoomWidth=a.offsetWidth||a.zoomWidth,a.zoomHeight=a.offsetHeight||a.zoomHeight,bs_R.Display("Seal",a.id,3>(window.innerWidth||b.clientWidth)/a.zoomWidth||3>(window.innerHeight||b.clientHeight)/a.zoomHeight?"Hide":"Show"))};bs_R.SimScroll=function(a){a.SimVert();a.SimHoriz()};
bs_R.SetPersist=function(a){function b(b){return(a[b]||0)+Math.abs(buySAFE[b]||0)}var d=a.ele,c=d.style,e=bs_R.oTarget,f="fixed"==c.position,g=bs_R.oDocElem,h={VT:"top",HL:"left",VB:"bottom",HR:"right",HC:"left"},k={VT:b("Top"),HL:b("Left"),VB:b("Bottom"),HR:b("Right"),Z:b("Z")};k.HC=k.VB;var l=bs_R.oSealRS;if(a.fRollover){var m="Responsive"==l.RolloverName,n=m?0:(l.fCustom?0.2:0.6)*e.width,l=m?0:l.fCustom?e.height-20:0.7*e.height;k.HL+=n;k.HR+=n;k.VT+=l;k.VB+=l}var r={VT:"_top:expression(document.body.scrollTop  + offsetHeight - offsetHeight + "+
k.VT+");",HL:"_left:expression(document.body.scrollLeft + offsetWidth  - offsetWidth  + "+k.HL+");",VB:"_top:expression(document.body.scrollTop  + document.body.clientHeight - offsetHeight    - "+k.VB+");",HR:"_left:expression(document.body.scrollLeft + document.body.clientWidth  - offsetWidth     - "+k.HR+");",HC:"_left:expression(document.body.scrollLeft + ((document.body.clientWidth  - offsetWidth)/2) - 0);"},l={VT:function(){c.top=pageYOffset+k.VT+"px"},HL:function(){c.left=pageXOffset+k.HL+"px"},
VB:function(){c.bottom=g.clientHeight-innerHeight-pageYOffset+k.VB+"px"},HR:function(){c.right=g.clientWidth-innerWidth-pageXOffset+k.HR+"px"},HC:function(){c.left=pageXOffset+(innerWidth-d.offsetWidth)/2+"px"},VBabs:function(){c.bottom=g.clientHeight-g.offsetHeight+"px"},HCabs:function(){c.left=(g.offsetWidth-d.offsetWidth)/2+"px"},HRabs:function(){c.right="0px"}};bs_R.fnCSS(c);c.position="fixed";c.left=c.right=c.top=c.bottom="auto";var m=a.sPosition,n="V"+m.charAt(0),m="H"+m.charAt(1),p=h[n],s=
h[m],v=h="";p&&s&&(h=p+":"+k[n]+"px;"+s+":"+k[m]+"px;",v=r[n]+r[m],c[p]=k[n]+"px",c[s]=k[m]+"px","HC"==m&&(h+="left:50%; margin-left:-"+parseInt(d.offsetWidth/2)+"px",c[s]="50%",c.marginLeft="-"+parseInt(d.offsetWidth/2)+"px"));e&&(e.tailVert=p,e.tailHoriz=s);bs_R.IsIEExpr?(e=" position: fixed; _position: absolute; ",buySAFE.HideSeal&&"none"==c.display&&(e+="display:none; "),e=bs_R.IsQuirks?e+v:e+h,c.cssText=bs_R.sBgDot+e,document.recalc&&document.recalc(!0)):bs_R.IsSimulated&&(c.marginLeft="0px",
e=d.id==bs_R.sBSGID?"abs":"",d.SimVert=l[n+e],d.SimHoriz=l[m+e],bs_R.SimScroll(d),bs_R.onDebounce(window,"scroll","SimScroll",function(){bs_R.SimScroll(d)}));f||bs_R.AddBody(d);a.fShadow&&(c.boxShadow=c.MozBoxShadow=c.WebkitBoxShadow=("HL"==m?"3px ":"-3px ")+("VB"==n?"-3px ":"3px ")+"3px -1px rgba(0,0,0,0.25)");c.zIndex=bs_R.nZIndex+k.Z;c.backgroundColor="transparent"};
bs_R.AdjustSeal=function(a,b,d,c,e,f){var g=bs_R._gel(b),h=bs_R._gel(a);"AltSeal"!=d&&g&&(g.setAttribute("wmode","transparent"),g.corner=f);bs_R._st(function(){var b=1<d||1<c,l=bs_R.oDocElem,m=bs_R.fPersist=parseInt(e);!m||!b&&buySAFE.StaticOffSeal||(h?(bs_R.SetPersist({ele:h,sPosition:f,Bottom:bs_R.oSealRS.Bottom,fShadow:bs_R.oSealRS.Shadow}),bs_R.iFrameFix(a,h),buySAFE.SealSpacer&&bs_R.BottomSpacer(90)):bs_R.err("WriteSeal: Can't find element: "+a));g?(g.style.width=(g.width=c)+"px",g.style.height=
(g.height=d)+"px",h&&(h.style.width=c+"px",h.style.height=d+"px",h.style.display="inline")):h&&(h.style.width=h.style.height="auto",buySAFE.HideSeal||(h.style.display="inline"));bs_R.SetTopMost(h);bs_R.ExecQueue("Seal");bs_R.Responsive(1);!m||buySAFE.HideSeal||buySAFE.NoZoomCheck||(bs_R.onDebounce(window,"resize","CheckZoom",function(){bs_R.CheckZoom(h,l)}),bs_R.onDebounce(window,"scroll","CheckZoom",function(){bs_R.CheckZoom(h,l)}),bs_R.CheckZoom(h,l))},bs_R.IsChr||bs_R.IsSaf?100:0)};
function AdjustBuysafeSealCallback(a,b,d,c,e,f,g){bs_R.AdjustSeal(a,b,d,c,e,f);a=bs_R.AltSealResponse(unescape(g));bs_R.oRollNames[b]=a.RolloverName;bs_R.RollRequest(a.RolloverName)}buySAFE.WriteSeal=WriteBuySafeSeal;
function WriteBuySafeSeal(a,b,d,c){a=a||"_GUARANTEE_SealSpan";b=b||"GuaranteedSeal";bs_R.T1=new Date;bs_R.fWS=!0;if(!bs_R.isDupe(a)){var e="buysafeseal_"+ ++bs_R.nSeals;if("PersistentSeal"==b||"GuaranteedSeal"==b)b="Large";if("Small"==a||"Medium"==a||"Large"==a)d=b,b=a,a="BS_FCompatibleSpan_"+ ++bs_R.nSeals,document.write('<span id="'+a+'"></span>');d||(d="HASH="+bs_R.Hash());var f=bs_R.SWF_Vars(d);bs_R.WriteFlash(a,e,function(){bs_R.AltSealTimeout(a,e,f.HASH,f.MSPHASH,b,"M")},1);bs_R.RollAttach(bs_R._geln("BuySafeButtonRollover"),
"Button","Button")}}buySAFE.WriteTrustSeal=WriteBuySafeTrustSeal;function WriteBuySafeTrustSeal(a,b,d,c,e,f,g,h,k,l){}buySAFE.WriteTrustRatingSeal=WriteBuySafeTrustRatingSeal;function WriteBuySafeTrustRatingSeal(a,b,d){}bs_R.GetDate=function(){var a=new Date,b=a.toLocaleDateString();b.match(/[a-z]/i)&&(b=a.toDateString().substring(4));return b};bs_R.CacheImg=function(a){a=bs_R.sRootImg+a;if(null==bs_R.oImgCache[a]){var b=new Image;b.src=a;bs_R.oImgCache[a]=b}};
bs_R.GetRolloverTail=function(a,b){return'<div style="'+bs_R.sCSS+"width:230px;height:47px;background: "+("url('"+bs_R.sRootImg+"rollover_tail.png')")+bs_R.oTail[b]+bs_R.oTail[a]+' no-repeat transparent;" oncontextmenu="return false;"></div>'};
bs_R.GetRolloverTemplate=function(a,b,d,c,e,f){bs_R.CacheImg(a);return{sBody:'<div style="'+bs_R.sCSS+"width:"+b+'px;position:relative;"><img src="'+bs_R.sRootImg+a+'" width="'+b+'" height="'+d+'" '+bs_R.sImgBlockCTX+'/><div style="'+bs_R.sRollText+" font-weight:normal;font-style:italic;color:#00305E;right:12px;bottom:"+f+'px;"><a style="color:#00305E;text-decoration:underline;" href="'+c+'" target="_blank">'+e+" &raquo;</a></div></div>"}};
bs_R.GetRolloverButton_2010_04=function(){return bs_R.GetRolloverTemplate("rollover_Button_2010_04.png",230,235,bs_R.sLandBond,"see terms and conditions",45)};
bs_R.RolloverGetHTML=function(a,b){function d(a,b){return'<div style="'+bs_R.sCSS+"position:absolute;top:0;left:0;bottom:0;right:0;z-index:-2;background:"+a+"; margin:"+b+';"></div>'}var c={sBody:"",sTail:""},e=bs_R.sRolloverType,f=bs_R.sRolloverName;if(bs_R.oSealRS.DisplayFlag&2){if("Button"==e)c=bs_R.GetRolloverButton_2010_04();else{var g=bs_R.oRollover.HTML[f]||"";"pending"==g&&(g="");c.sBody=g}"Seal"==e&&"AttentionRequired"==f&&(c.sTail='<div><img src="'+bs_R.sRootImg+"atnrq_tail_"+a+"_"+b+'.gif" alt="" '+
bs_R.sImgBlockCTX+" /></div>");c.sBody&&!c.sTail&&(c.sTail=bs_R.GetRolloverTail(a,b))}c.sBody&&!bs_R.oSealRS.Custom&&(c.sBody='<div style="'+bs_R.sCSS+'position:relative;">'+c.sBody+d("#002f5f","5px 0")+d("#002f5f","0 5px")+d("#002f5f","2px")+"</div>");bs_R.oSealRS.Custom&&"Button"!=e&&(c.sTail="");return"top"==a?c.sTail+c.sBody:c.sBody+c.sTail};bs_R.WriteHTMLVAR=function(a){for(var b,d=/\[VAR_([^\]]+)]/;b=d.exec(a);)a=a.replace(b[0],eval(b[1]));return a};
bs_R.WriteKickersHTML=function(a,b){if(a){var d=bs_R._gel(a);if(d){d.innerHTML=bs_R.WriteHTMLVAR(b);for(var c=bs_R.oRollNames[a],e=/^Rollover_(.*)$/i,f=d.getElementsByTagName("span"),g=0;!c&&g<f.length;g++){var h=f[g];if(h){var k=e.exec(h.id);k&&k[1]&&(c=k[1],d.removeChild(h))}}buySAFE.NoKickerRollover||c&&bs_R.RollAttach([d],c);bs_R.ExecQueue("Kicker",a);bs_R.Responsive(1,a)}else bs_R.err("WriteKickers: Can't find element: "+a)}};
bs_R.GetKicker=function(a,b,d){bs_R.AddJS(bs_R.sRootSeal+"Dynamic.aspx?CBF=bs_R.WriteKickersHTML&"+bs_R.EncodeQuery({encode:{Promocode:a,ifID:b},raw:{DP:bs_R.getDevicePrint(d),HASH:bs_R.Hash()}})+(a.match(/Rating/)?"&e=e&PK="+bs_R.oSealRS.MPUHash:""))};bs_R.GetKickers=function(){for(var a=[],b=bs_R.aKickID,d=0;d<b.length;d++)for(var c=bs_R._geln(b[d]),e=0;e<c.length;e++)a.push(c[e]);return a};
bs_R.InsertKickers=function(){var a={pN:"parentNode",fC:"firstChild",lC:"lastChild",nS:"nextSibling"},b={Before:function(a,b){a.parentNode.insertBefore(b,a.parentNode.firstChild)},After:function(a,b){a.parentNode.insertBefore(b,a.nextSibling)},First:function(a,b){a.insertBefore(b,a.firstChild)},Last:function(a,b){a.appendChild(b)}},d=_GUARANTEE.InsertKickers;if(d&&d.length)for(var c=0;c<d.length;c++){var e=d[c],f=e.anchorTagName,g=e.anchorID,h=e.anchorClass,k=e.kickerStyle,l=e.containerTagName,m=
e.containerStyle,n=e.path,r=e.kickerType,p=0;if(!e.done&&(g?p=bs_R._gel(g):!p&&h&&(p=bs_R.GetByClass(h,f)[0]),p)){for(f=0;f<n.length;f++)if(h=n[f],(g=a[h])&&p[g])p=p[g];else if(h=h.match(/^c(\d+)(b)?$/i))for(var g=h[1],h=h[2],s=p.childNodes,v=s.length-1,u=h?v:0,h=h?-1:1,q=0;u<=v;u+=h)if(1==s[u].nodeType){if(q==g){p=s[u];break}q++}n=bs_R._cel("span");n.id=bs_R.aKickID[1];n.setAttribute("name",n.id);n.setAttribute("type",r);k&&(n.style.cssText=k);k=n;l&&(l=bs_R._cel(l),m&&(l.style.cssText=m),l.appendChild(n),
k=l);if(m=b[e.loc])m(p,k),e.done=1}}};
bs_R.WriteKickers=function(){bs_R.nKickerPass++;bs_R.InsertKickers();for(var a=buySAFE,b=RegExp(bs_R.aKickID.join("|")),d={},c=bs_R.GetKickers(),e=0;e<c.length;e++){var f=c[e];if(f&&f.id.match(b)){var g=(f.getAttribute("type")||"").match(/(?:\((.*)\) )?(.*)/),h=g[2],k=h+"_"+ ++bs_R.nKicker;bs_R.oRollNames[k]=g[1];a.HideKickers&&(f.style.display="none");"none"!=f.style.display&&(f.style.display="inline-block");"Kicker Dynamic"==h&&a.EnableClientDisplay&&(bs_R.determineKickerName(d,a),d.kn&&(h=d.kn));
f.setAttribute("name",h);f.id=k;bs_R.GetKicker(h,k,d)}}1<bs_R.nKickerPass&&!bs_R.nKicker&&bs_R.GetKicker("Kicker Custom Null","",d)};bs_R.AltKickers=function(a,b,d,c,e,f,g){bs_R.AltSealResponse(g)};buySAFE.WriteKickers=WriteBuySafeKickers;function WriteBuySafeKickers(){bs_R.fWK=!0;var a=bs_R.Hash();if(a&&String(a).match(/^eaccEkXk206%2BSGpYrAUoGhA2Bxg%2F/i))return!1;bs_R.AltSealInfo("bs_R.AltKickers","ele","seal",a,"","Large","")}
bs_R.Display=function(a,b,d,c,e){var f={Seal:"inline",Kicker:"inline-block"},g=bs_R._gel(b),h=bs_R.oSealRS.Stream;if(g){if(f=f[a])g.style.display="Hide"==d?"none":f;"Kicker"==a&&c&&((f=g.getElementsByTagName("img")[0])&&h?(c=c.replace(/(?:kicker|custom)[ _]*/ig,""),f.src=h+"&R=0&x="+c,bs_R.RollAttach([g],"Kicker_Custom_"+c)):bs_R.aExecQ.push(["Display",buySAFE,arguments]))}else e||bs_R.err("Display: Can't find element: "+b)};
buySAFE.Display=function(a,b,d,c,e){"Seal"==a&&(buySAFE.NoZoomCheck=1);bs_R.Display(a,b,d,c,e)};
bs_R.iFrameFix=function(a,b,d){if(!buySAFE.NoIFrame&&a&&b){var c=bs_R.oFrameFix[a];c||(c=bs_R._cel("iframe"),c.id=a+"_frame",c.title="Unused iFrame "+bs_R.niFrame++,c.tabIndex=-1,c.frameBorder=c.marginHeight=c.marginWidth=0,c.scrolling="no",bs_R.oFrameFix[a]=c);var e=c.style;bs_R.fnCSS(e);e.position="absolute";c.width=c.height=e.width=e.height="1px";e.top=e.left=0;e.zIndex=-2;d&&(e.background=d);e.filter="progid:DXImageTransform.Microsoft.Alpha(opacity=0)";b.appendChild(c);c.width=c.height=e.width=
e.height="100%";bs_R.IsIEQuirks&&bs_R._st(function(){c.height=e.height=b.clientHeight+"px"},500)}};bs_R.RollHide=function(a){if(a=a||bs_R._gel(bs_R.sRolloverID)){var b=a.style,d="position:absolute;visibility:hidden;transition:none;";b.cssText=d;bs_R.IsIEExpr&&(b.cssText=d+"_top:expression(0); _left:expression(0);",document.recalc&&document.recalc(!0));b.top=b.left="-1000px";b.bottom=b.right="auto";a.onmouseover=a.onmouseout=a.onclick=function(){}}};
bs_R.RollGet=function(){var a=bs_R._gel(bs_R.sRolloverID);a||(a=bs_R._cel("div"),a.id=bs_R.sRolloverID,bs_R.RollHide(a),bs_R.AddBody(a));return a};bs_R.RollStop=function(a,b){a&&a[b]&&(clearTimeout(a[b]),a[b]=0)};
bs_R.RollShow=function(){var a=bs_R.oSealRS,b=bs_R.sRolloverType,d=bs_R.sRolloverName,c="Responsive"==d;bs_R.trc({src:"rollover",name:d});var e=bs_R.RollGet();e.onmouseover=function(a){bs_R.RollStop(bs_R.oRollover[d],"hide")};e.onmouseout=e.onclick=function(a){a=a||window.event;var b=bs_R.oRollover[d];if(c)return 0;var e="click"==a.type;e&&(b.X=a.clientX,b.Y=a.clientY);buysafeOut(0,e?1:0)};e.innerHTML=bs_R.RolloverGetHTML("top","left");var f,g,h=e.style;h.transition="none";h.zIndex=bs_R.nZIndex;bs_R.fnCSS(h);
if(!bs_R.fPersist||"Seal"!=b&&"Guarantee"!=b){h.position="absolute";h.top=h.left=0;h.bottom=h.right="";g=bs_R.GetTarget(bs_R.oTarget);var k=bs_R.oDocElem;f=(window.pageYOffset||k.scrollTop)+k.clientHeight/2;var k=(window.pageXOffset||k.scrollLeft)+k.clientWidth/2,l=g.top+g.offsetHeight/2,m=g.left+g.offsetWidth/2;a.Custom&&"Button"!=b?(h.top=g.top+"px",h.left=g.left+"px",f="bottom",g="right"):(l>f?(h.top=g.top-e.offsetHeight+0+"px",f="bottom"):(h.top=g.top+g.offsetHeight-0+"px",f="top"),m>k?(h.left=
g.left-e.offsetWidth+0+"px",g="right"):(h.left=g.left+g.offsetWidth-0+"px",g="left"))}else bs_R.SetPersist({ele:e,sPosition:bs_R.oTarget.corner,Bottom:a.Bottom,fShadow:a.Shadow,fRollover:1,Z:100}),f=bs_R.oTarget.tailVert,g=bs_R.oTarget.tailHoriz;e.tailVert=f;e.innerHTML=bs_R.RolloverGetHTML(f,g);c&&bs_R.oBSG.WriteResponsive(b,d,a);h.visibility="visible";bs_R.iFrameFix(bs_R.sRolloverID,e)};bs_R.RollOver2=function(a,b){var d=bs_R.oRollover[b];d&&d.show&&(bs_R.RollStop(d,"show"),a())};
bs_R.RollOut2=function(a,b){var d=bs_R.oRollover[b];d&&d.hide&&(bs_R.RollStop(d,"hide"),a())};bs_R.RollOver=function(a,b){b=b||bs_R.sRolloverName;var d=bs_R.oRollover[b];bs_R.RollStop(d,"hide");d&&!d.show&&(d.show=bs_R._st(function(){bs_R.RollOver2(a,b||bs_R.sRolloverName)},bs_R.nShowTime))};bs_R.RollOut=function(a,b){b=b||bs_R.sRolloverName;var d=bs_R.oRollover[b];bs_R.RollStop(d,"show");d&&!d.hide&&(d.hide=bs_R._st(function(){bs_R.RollOut2(a,b)},bs_R.nHideTime))};
function buysafeOver(a,b,d,c,e){buySAFE.NoRollover||"GenericT"==a||("IMG"!=b.tagName||2<b.naturalWidth||2<b.clientWidth?(bs_R.sRolloverQuery=c,a=bs_R.sRolloverName=bs_R.oRollNames[b.id]||a,bs_R.sRolloverType=d,bs_R.oTarget=b,bs_R.oRollover[a]=bs_R.oRollover[a]||{},e?bs_R.RollShow():bs_R.RollOver(bs_R.RollShow)):b.onclick=function(){return!1})}function buysafeOut(a,b){b?bs_R.RollHide():bs_R.RollOut(bs_R.RollHide)}function buysafeFlashOver(a,b,d){buysafeOver(a,bs_R._gel(b),null==d?"Button":d)}
function buysafeTrustRatingFlashOver(a,b,d,c){buysafeOver(a,bs_R._gel(b),null==d?"Button":d,c)}function buysafeButtonFlashOver(a,b,d,c){buysafeOver(a,bs_R._gel(b),null==d?"Button":d,c)}
(function(a,b){a.RollCBF=function(b,c){var e=a.oRollover;e.RAW[b]=c;e.HTML[b]=a.WriteHTMLVAR(c);var f=a.RollGet();"hidden"==f.style.visibility&&(f.innerHTML=e.HTML[b],f.innerHTML="")};a.RollRequest=function(b){b&&!a.oRollover.HTML[b]&&(a.oRollover.HTML[b]="pending",a.AddJS(a.sRootSeal+"Static.aspx?CBF=bs_R.RollCBF&Type=RO&"+a.EncodeQuery({encode:{},raw:{Promocode:b,ifID:b,DP:a.getDevicePrint(),HASH:a.Hash()}})))};a.RollAttach=function(b,c,e,f){for(var g,h=0;h<b.length;h++){g=b[h];g.onmouseover=function(b){b=
b||window.event;var d=a.oRollover[c]||{};a.RollStop(d,"show");a.RollStop(d,"hide");var g="click"==b.type;(g||d.X!=b.clientX||d.Y!=b.clientY)&&buysafeOver(c,this,e,f,g?1:0)};g.onmouseout=function(a){buysafeOut()};if("Seal"==e&&"Responsive"==c||c.match(/^Kicker_/))g.onclick=g.onmouseover;a._ctx(g)}g&&a.RollRequest(c)};a.ExecQueue=function(b,c){for(var e,f=0,g=a.aExecQ.length;f++<g&&(e=a.aExecQ.shift());)"Display"==e[0]&&(e[2][0]!=b||c&&e[2][1]!=c)?a.aExecQ.push(e):e[1][e[0]].apply(null,e[2])};a.Responsive=
function(d,c){var e=b.Responsive;if(e){var f=e.Kickers,g=e.Seal||{},h=e.Breakpoints?1:0,k=(h?e.Breakpoints:f.widths)||[],l=(h?f:f.ids)||{},m=(h?k[g.Breakpoint-1]:g.width)||0,n=0,r;if(f&&k)for(;n<k.length&&!((r=a.oDocElem.clientWidth)<=k[n]);)n++;if(n!=e.State||d){e.State=n;if(f&&l)for(var p in l)c&&c!=p||(e=h?l[p][n]:n+l[p],a.Display("Kicker",p,e?"Show":"Hide","Kicker Custom "+e,1));!g.id||c&&c!=g.id||(b.NoZoomCheck=1,a.Display("Seal",g.id,r<=m?"Hide":"Show"))}}}})(bs_R,buySAFE);
bs_R.SetBrowser=function(a,b){a.oBrowser=a.oBrowser||{str:function(a){for(var c=0;c<a.length;c++){var e=a[c],f=e.src||b.userAgent,g=e.re||e.name;this.tmp=e.ver||e.name;if(f.match(g))return e.name}return""},ver:function(a){return(a=a.match(this.tmp+".([\\d\\.\\-]+)"))?a[1]:""},init:function(d){if(!d.name){var c=b.platform,c=[{name:"Windows",src:c,re:"Win"},{name:"Mac",src:c},{name:"Android"},{name:"iOS",re:"iPhone|iPad|iPod"},{name:"Linux",src:c}];d.name=d.str([{name:"Chrome"},{name:"Chromium"},{name:"Safari",
ver:"Android",re:"Android.*Safari"},{name:"Safari",ver:"Version"},{name:"Opera",ver:"Version"},{name:"Firefox"},{name:"Netscape"},{name:"IEMobile"},{name:"MSIE"},{name:"MSIE",ver:"rv",re:"Trident"}]);d.version=d.ver(b.userAgent)||d.ver(b.appVersion);d.vr=parseFloat(d.version);d.os=d.str(c);a.IsAnd="Android"==d.os;a.IsiOS="iOS"==d.os;a.IsSaf="Safari"==d.name;a.IsChr="Chrome"==d.name;a.IsIE="MSIE"==d.name;a.IsFF="Firefox"==d.name;a.IsIE6=a.IsIE&&6==d.vr;a.IsIElt8=a.IsIE&&8>d.vr;a.IsIElt10=a.IsIE&&10>
d.vr;a.IsTouch=a.IsiOS||a.IsAnd;a.IsSimulated=a.IsiOS&&5.1>d.vr||a.IsAnd&&a.IsSaf&&4>d.vr;a.IsQuirks="BackCompat"==document.compatMode;a.IsIEQuirks=a.IsIE&&a.IsQuirks;a.IsIEExpr=a.IsIElt8||a.IsIEQuirks&&a.IsIElt10}}};a.oBrowser.init(a.oBrowser)};
(function(a,b){if(!a.fLoaded){a.fLoaded=1;a.T0=new Date;a.sRolloverID="buysafeRollover";a.sBSGID="BuySafeGuaranteeSpan";a.sRespID="bs_iframe_responsive";a.sNSG="Norton Shopping Guarantee";a.sBSG="buySAFE Guarantee";a.aKickID=["buySAFE_Kicker","_GUARANTEE_Kicker"];a.sT="Ter";a.nPersistH=70;a.nPersistW=80;a.fPersist=!1;a.nShowTime=500;a.nHideTime=500;a.oRollover={HTML:{},RAW:{}};a.oSealRS={DisplayFlag:1026};a.iiQ=[];a.sDate=a.GetDate();a.nResponsiveH="350px";var d=a.sRootHost;a.sRootHostWWW=d.replace(/\/\/nsg\.symantec\./i,
"//my.NortonShoppingGuarantee.").replace(/\/\/seal\./i,"//www.").replace("http:","https:");a.sRootImg=a.sRoot+"images/";a.sRootSeal=d+"/Web/Seal/";a.sRootSealImg=a.sRootSeal+"images/";a.sRootSealImgBSG=a.sRootSealImg+"bsg/";a.sRootVer=d+"/Web/Verification/";a.sWebVer=a.sRootHostWWW+"/Web/Verification/VerifyTrustSeal.aspx";a.sVerify=a.sRootHostWWW+"/Web/Seal/VerifySeal.aspx";a.nSeals=0;a.niFrame=1;a.oObjs={};a.oRollNames={};a.nKicker=0;a.nKickerPass=0;a.oImgCache={};a.oTail={top:" 0px",bottom:" -47px",
left:" -35px",right:" 195px"};var c=a.sCSS="border:0;margin:0;padding:0;";a.fnCSS=function(a){a.border=a.margin=a.padding="0"};a.sNoPin="data-pin-no-hover";var e=' oncontextmenu="return false;" '+a.sNoPin+'="true" style="'+c+"visibility:inherit;";a.sImgCTX=e+'" ';a.sImgBlockCTX=e+'display:block;" ';a.sFont=" font-family:Verdana,Arial,Helvetica,sans-serif;text-decoration:none;text-indent:0;text-transform:none;word-spacing:normal;letter-spacing:normal;";a.sRollText=a.sFont+"font-size:10px;text-align:right;position:absolute;"+
c;a.sBgDot=" background: url('"+d+"/images/dot.gif') fixed right bottom no-repeat; ";a.sFrameDef=' style="display:block;visibility:visible;'+c+'" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" vspace="0" allowtransparency="true" ';a.sTable='<table border="0" cellpadding="0" cellspacing="0" ';a.oTimeouts={};a.fFlashPlaceholder=!1;a.sWeb4=a.sRootHost+"/Web4/Seal/";a.sPageHost=a._l.host.replace("www.","");a.oFrameFix={};a.oDebounce={};a.SetBrowser(a,navigator);b.Variation&&(b.Variation=
String(b.Variation).toLowerCase());(b.HideAll||a.IsIE6||"off"==b.Variation)&&a.HideAll(b);a.IsTouch&&(b.Guarantee.hidden=1);a.nZIndex=a.isUndef(b.zIndex,10001);a.nKickTime=a.isUndef(b.KickerDelay,200);a.oDocElem=a.IsQuirks?document.body:document.documentElement;a.ExecQueue();if(b.Responsive)a.onDebounce(window,"resize","Responsive",function(){a.Responsive()})}})(bs_R,buySAFE);bs_R.RollAttach(bs_R._geln("buySAFE Bonded Seller"),"Seller");
